django_crash/django_crash/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('todo_list.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) # tells Django to serve static files from the STATIC_ROOT folder on dev server

django_crash/todo_list/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.todo_list, name='todo_list'),
    path('add', views.add_task, name='add_task'),
    path('task/<int:pk>', views.task_detail, name='task_detail'),
    path('edit/<int:pk>', views.edit_task, name='edit_task'),
    path('delete/<int:pk>', views.delete_task, name='delete_task'),
]

django_crash/todo_list/models.py
from django.db import models

class TodoItem(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField(max_length=2000)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.title

django_crash/todo_list/forms.py
from django import forms
from .models import TodoItem

class TodoForm(forms.ModelForm):
    class Meta:
        model = TodoItem
        fields = ['title', 'description', 'completed']
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Enter title...'}),
            'description': forms.Textarea(attrs={'placeholder': 'Enter description...', 'rows': 6}),
            'completed': forms.CheckboxInput(),
        }

django_crash/todo_list/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import TodoItem
from .forms import TodoForm

def todo_list(request):
    todos = TodoItem.objects.all()
    return render(request, 'todo-list.html', { 'todos': todos })

def add_task(request):
    if request.method == 'POST':
        form = TodoForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('todo_list')
    else:
        form = TodoForm()

    return render(request, 'add-task.html', { 'form': form })

def task_detail(request, pk):
    task = get_object_or_404(TodoItem, pk=pk)
    return render(request, 'task-detail.html', { 'task': task })

def edit_task(request, pk):
    task = get_object_or_404(TodoItem, pk=pk)
    
    if request.method == 'POST':
        form = TodoForm(request.POST, instance=task)

        if form.is_valid():
            form.save()
            return redirect('task_detail', pk=task.pk)
    else:
        form = TodoForm(instance=task)

    return render(request, 'edit-task.html', { 'form': form, 'task': task })

def delete_task(request, pk):
    task = get_object_or_404(TodoItem, pk=pk)

    if request.method == 'POST':
        task.delete()
        return redirect('todo_list')
    
    return render(request, 'delete-task.html', { 'task': task })

django_crash/todo_list/templates/add-task.html
{% extends "base.html" %}

{% block title %}Add Task{% endblock %}

{% block content %}
    <h1>Add Task</h1>
    {% comment %} <form method="post" action="{% url "add_task" %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add Task</button>
    </form> {% endcomment %}


    <form method="post" action="{% url "add_task" %}">
        {% csrf_token %}
        <div class="form-control">
            <label for="id_title">Title</label>
            {{ form.title }}
        </div>
        <div class="form-control">
            <label for="id_description">Description</label>
            {{ form.description }}
        </div>
        <div class="form-control">
            <label for="id_completed">Task completed?</label>
            {{ form.completed }}
        </div>
        <button type="submit">Add Task</button>
    </form>

    <a href="{% url "todo_list" %}" alt="back to home">Back to Home</a>
{% endblock %}

django_crash/todo_list/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}To-Do List{% endblock %}</title>

    <!-- Google fonts -->
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700&display=swap" rel="stylesheet">

    <!-- Font Awesome icons -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">

    <link rel="stylesheet" href="{% static "style.css" %}">
</head>
<body>
    <main class="container">
        {% block content %}{% endblock %}
    </main>
</body>
</html>

django_crash/todo_list/templates/delete-task.html
{% extends "base.html" %}

{% block title %}Delete {{ task.title }}?{% endblock %}

{% block content %}
    <h1>Delete "{{ task.title }}"</h1>
    <p>Are you sure you want to delete this task?</p>
    <form method="post" action="{% url "delete_task" pk=task.pk %}" class="delete-form">
        {% csrf_token %}
        <div class="actions">
            <button class="btn-danger">Yes, delete</button>
            <a href="{% url "todo_list" %}">Cancel</a>
        </div>
    </form>
{% endblock %}

django_crash/todo_list/templates/edit-task.html
{% extends "base.html" %}

{% block title %}Edit {{ task.title }}{% endblock %}

{% block content %}
    <h1>Edit "{{ task.title }}"</h1>
    <form method="post" action="{% url "edit_task" pk=task.pk %}">
        {% csrf_token %}
        <div class="form-control">
            <label for="id_title">Title</label>
            {{ form.title }}
        </div>
        <div class="form-control">
            <label for="id_description">Description</label>
            {{ form.description }}
        </div>
        <div class="form-control">
            <label for="id_completed">Task completed?</label>
            {{ form.completed }}
        </div>
        <button class="btn-submit" type="submit">Update Task</button>
    </form>

    <a href="{% url "todo_list" %}" alt="back to home">Back to Home</a>
{% endblock %}

django_crash/todo_list/templates/task-detail.html
{% extends "base.html" %}

{% block title %}{{ task.title }}{% endblock %}

{% block content %}
    <div class="todos-heading">
        <h1>{{ task.title }}</h1>
        {% if task.completed %}
            <span class="badge">
                <i class="fas fa-check"></i>
                Task complete
            </span>
        {% endif %}
    </div>
    <p>{{ task.description }}</p>
    <a href="{% url "todo_list" %}" alt="add task">Back to Home</a>
{% endblock %}

django_crash/todo_list/templates/todo-list.html
{% extends "base.html" %}

{% block title %}To-Do Home{% endblock %}

{% block content %}
    <div class="todos-heading">
        <h1>To-Do List</h1>
        <a href="{% url "add_task" %}">
            <button>Add New Task</button>
        </a>
    </div>
    <div class="todos">
        {% for task in todos %}
            <p class="todo-item">
                <a href="{% url "task_detail" pk=task.pk %}" alt="{{ task.title }}">{{ task.title }}</a>
                <span class="actions">
                    <a href="{% url "edit_task" pk=task.pk %}">Edit</a>
                    <a href="{% url "delete_task" pk=task.pk %}">Delete</a>
                </span>
            </p>
        {% endfor %}
    </div>
{% endblock %}